CREATE DATABASE IF NOT EXISTS `jegyzetar` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;
USE `jegyzetar`;

CREATE TABLE IF NOT EXISTS `badges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `slug` varchar(64) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `icon` varchar(16) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userid` int(11) NOT NULL,
  `postid` int(11) NOT NULL,
  `text` varchar(1000) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `favorites` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `file_id` int(11) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `files` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uploaded_by` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `file_path` varchar(255) NOT NULL,
  `subject` varchar(100) NOT NULL,
  `tags` varchar(255) NOT NULL,
  `tn_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `friends` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fromid` int(11) NOT NULL,
  `toid` int(11) NOT NULL,
  `status` tinyint(4) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `languages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(5) NOT NULL,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

INSERT INTO `languages` (`id`, `code`, `name`) VALUES
(1, 'hu', 'Magyar'),
(2, 'en', 'English'),
(3, 'de', 'Deutsch')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`);

CREATE TABLE IF NOT EXISTS `messages` (
  `id` int(255) NOT NULL,
  `fromid` int(255) NOT NULL,
  `toid` int(255) NOT NULL,
  `content` text NOT NULL,
  `sent_at` date NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `namedays` (
  `id` int(11) NOT NULL,
  `datum` varchar(5) DEFAULT NULL,
  `nevek` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

INSERT INTO `namedays` (`id`, `datum`, `nevek`) VALUES
(1, '01-01', 'Fruzsina'),
(2, '01-02', 'Ábel'),
(3, '01-03', 'Benjámin, Genovéva'),
(4, '01-04', 'Leóna, Titusz'),
(5, '01-05', 'Simon'),
(6, '01-06', 'Boldizsár'),
(7, '01-07', 'Attila, Ramóna'),
(8, '01-08', 'Gyöngyvér'),
(9, '01-09', 'Marcell'),
(10, '01-10', 'Melánia'),
(11, '01-11', 'Ágota'),
(12, '01-12', 'Ernő'),
(13, '01-13', 'Veronika'),
(14, '01-14', 'Bódog'),
(15, '01-15', 'Lóránd, Lóránt'),
(16, '01-16', 'Gusztáv'),
(17, '01-17', 'Antal, Antónia'),
(18, '01-18', 'Piroska'),
(19, '01-19', 'Márió, Sára'),
(20, '01-20', 'Fábián, Sebestyén'),
(21, '01-21', 'Ágnes'),
(22, '01-22', 'Artúr, Vince'),
(23, '01-23', 'Rajmund, Zelma'),
(24, '01-24', 'Timót'),
(25, '01-25', 'Pál'),
(26, '01-26', 'Paula, Vanda'),
(27, '01-27', 'Angelika'),
(28, '01-28', 'Karola, Károly'),
(29, '01-29', 'Adél'),
(30, '01-30', 'Martina'),
(31, '01-31', 'Gerda, Marcella'),
(32, '02-01', 'Ignác'),
(33, '02-02', 'Aida, Karolina'),
(34, '02-03', 'Balázs'),
(35, '02-04', 'Csenge, Ráhel'),
(36, '02-05', 'Ágota, Ingrid'),
(37, '02-06', 'Dóra, Dorottya'),
(38, '02-07', 'Rómeó, Tódor'),
(39, '02-08', 'Aranka'),
(40, '02-09', 'Abigél, Alex'),
(41, '02-10', 'Elvira'),
(42, '02-11', 'Bertold, Marietta'),
(43, '02-12', 'Lídia, Lívia'),
(44, '02-13', 'Ella, Linda'),
(45, '02-14', 'Bálint, Valentin'),
(46, '02-15', 'Georgina, Kolos'),
(47, '02-16', 'Julianna, Lilla'),
(48, '02-17', 'Donát'),
(49, '02-18', 'Bernadett'),
(50, '02-19', 'Zsuzsanna'),
(51, '02-20', 'Aladár, Álmos'),
(52, '02-21', 'Eleonóra'),
(53, '02-22', 'Gerzson'),
(54, '02-23', 'Alfréd'),
(55, '02-24', 'Mátyás'),
(56, '02-25', 'Géza'),
(57, '02-26', 'Edina'),
(58, '02-27', 'Ákos, Bátor'),
(59, '02-28', 'Elemér'),
(60, '03-01', 'Albin'),
(61, '03-02', 'Lujza'),
(62, '03-03', 'Kornélia'),
(63, '03-04', 'Kázmér'),
(64, '03-05', 'Adorján, Adrián'),
(65, '03-06', 'Inez, Leonóra'),
(66, '03-07', 'Tamás'),
(67, '03-08', 'Zoltán'),
(68, '03-09', 'Fanni, Franciska'),
(69, '03-10', 'Ildikó'),
(70, '03-11', 'Szilárd'),
(71, '03-12', 'Gergely'),
(72, '03-13', 'Ajtony, Krisztián'),
(73, '03-14', 'Matild'),
(74, '03-15', 'Kristóf'),
(75, '03-16', 'Henrietta'),
(76, '03-17', 'Gertrúd, Patrik'),
(77, '03-18', 'Ede, Sándor'),
(78, '03-19', 'Bánk, József'),
(79, '03-20', 'Klaudia'),
(80, '03-21', 'Benedek'),
(81, '03-22', 'Beáta, Izolda'),
(82, '03-23', 'Emőke'),
(83, '03-24', 'Gábor, Karina'),
(84, '03-25', 'Irén, Írisz'),
(85, '03-26', 'Emánuel'),
(86, '03-27', 'Hajnalka'),
(87, '03-28', 'Gedeon, Johanna'),
(88, '03-29', 'Auguszta'),
(89, '03-30', 'Zalán'),
(90, '03-31', 'Árpád'),
(91, '04-01', 'Hugó'),
(92, '04-02', 'Áron'),
(93, '04-03', 'Buda, Richárd'),
(94, '04-04', 'Izidor'),
(95, '04-05', 'Vince'),
(96, '04-06', 'Bíborka, Vilmos'),
(97, '04-07', 'Herman'),
(98, '04-08', 'Dénes'),
(99, '04-09', 'Erhard'),
(100, '04-10', 'Zsolt'),
(101, '04-11', 'Leó, Szaniszló'),
(102, '04-12', 'Gyula'),
(103, '04-13', 'Ida'),
(104, '04-14', 'Tibor'),
(105, '04-15', 'Anasztázia, Tas'),
(106, '04-16', 'Csongor'),
(107, '04-17', 'Rudolf'),
(108, '04-18', 'Andrea, Ilma'),
(109, '04-19', 'Emma'),
(110, '04-20', 'Tivadar'),
(111, '04-21', 'Konrád'),
(112, '04-22', 'Csilla, Noémi'),
(113, '04-23', 'Béla'),
(114, '04-24', 'György'),
(115, '04-25', 'Márk'),
(116, '04-26', 'Ervin'),
(117, '04-27', 'Zita'),
(118, '04-28', 'Valéria'),
(119, '04-29', 'Péter'),
(120, '04-30', 'Katalin, Kitti'),
(121, '05-01', 'Fülöp, Jakab'),
(122, '05-02', 'Zsigmond'),
(123, '05-03', 'Irma, Tímea'),
(124, '05-04', 'Flórián, Mónika'),
(125, '05-05', 'Adrián, Györgyi'),
(126, '05-06', 'Frida, Ivett'),
(127, '05-07', 'Gizella'),
(128, '05-08', 'Mihály'),
(129, '05-09', 'Gergely'),
(130, '05-10', 'Ármin, Pálma, Mira'),
(131, '05-11', 'Ferenc'),
(132, '05-12', 'Pongrác'),
(133, '05-13', 'Imola, Szervác'),
(134, '05-14', 'Bonifác'),
(135, '05-15', 'Szonja, Zsófia'),
(136, '05-16', 'Botond, Mózes'),
(137, '05-17', 'Paszkál'),
(138, '05-18', 'Alexandra, Erik'),
(139, '05-19', 'Ivó, Milán'),
(140, '05-20', 'Bernát, Felícia'),
(141, '05-21', 'Konstantin'),
(142, '05-22', 'Júlia, Rita'),
(143, '05-23', 'Dezső'),
(144, '05-24', 'Eliza, Eszter'),
(145, '05-25', 'Orbán'),
(146, '05-26', 'Evelin, Fülöp'),
(147, '05-27', 'Hella'),
(148, '05-28', 'Csanád, Emil'),
(149, '05-29', 'Magdolna'),
(150, '05-30', 'Janka, Zsanett'),
(151, '05-31', 'Angéla'),
(152, '06-01', 'Tünde'),
(153, '06-02', 'Anita, Kármen'),
(154, '06-03', 'Klotild'),
(155, '06-04', 'Bulcsú'),
(156, '06-05', 'Fatime'),
(157, '06-06', 'Cintia, Norbert'),
(158, '06-07', 'Róbert'),
(159, '06-08', 'Medárd'),
(160, '06-09', 'Félix'),
(161, '06-10', 'Gréta, Margit'),
(162, '06-11', 'Barnabás'),
(163, '06-12', 'Villő'),
(164, '06-13', 'Anett, Antal'),
(165, '06-14', 'Vazul'),
(166, '06-15', 'Jolán, Vid'),
(167, '06-16', 'Jusztin'),
(168, '06-17', 'Alida, Laura'),
(169, '06-18', 'Arnold, Levente'),
(170, '06-19', 'Gyárfás'),
(171, '06-20', 'Rafael'),
(172, '06-21', 'Alajos, Leila'),
(173, '06-22', 'Paulina'),
(174, '06-23', 'Zoltán'),
(175, '06-24', 'Iván'),
(176, '06-25', 'Vilmos'),
(177, '06-26', 'János, Pál'),
(178, '06-27', 'László'),
(179, '06-28', 'Irén, Levente'),
(180, '06-29', 'Péter, Pál'),
(181, '06-30', 'Pál'),
(182, '07-01', 'Annamária, Tihamér'),
(183, '07-02', 'Ottó'),
(184, '07-03', 'Kornél, Soma'),
(185, '07-04', 'Ulrik'),
(186, '07-05', 'Emese, Sarolta'),
(187, '07-06', 'Csaba'),
(188, '07-07', 'Apollónia'),
(189, '07-08', 'Ellák'),
(190, '07-09', 'Lukrécia'),
(191, '07-10', 'Amália'),
(192, '07-11', 'Lili, Nóra'),
(193, '07-12', 'Dalma, Izabella'),
(194, '07-13', 'Jenő'),
(195, '07-14', 'Örs, Stella'),
(196, '07-15', 'Henrik, Roland'),
(197, '07-16', 'Valter'),
(198, '07-17', 'Elek, Endre'),
(199, '07-18', 'Frigyes'),
(200, '07-19', 'Emília'),
(201, '07-20', 'Illés'),
(202, '07-21', 'Dániel, Daniella'),
(203, '07-22', 'Magdolna'),
(204, '07-23', 'Lenke'),
(205, '07-24', 'Kincső, Kinga'),
(206, '07-25', 'Jakab, Kristóf'),
(207, '07-26', 'Anikó, Anna'),
(208, '07-27', 'Liliána, Olga'),
(209, '07-28', 'Szabolcs'),
(210, '07-29', 'Flóra, Márta'),
(211, '07-30', 'Judit, Xénia'),
(212, '07-31', 'Oszkár'),
(213, '08-01', 'Boglárka'),
(214, '08-02', 'Lehel'),
(215, '08-03', 'Hermina'),
(216, '08-04', 'Dominika, Domonkos'),
(217, '08-05', 'Krisztina'),
(218, '08-06', 'Berta, Bettina'),
(219, '08-07', 'Ibolya'),
(220, '08-08', 'László'),
(221, '08-09', 'Emőd'),
(222, '08-10', 'Lőrinc'),
(223, '08-11', 'Tiborc, Zsuzsanna'),
(224, '08-12', 'Klára'),
(225, '08-13', 'Ipoly'),
(226, '08-14', 'Marcell'),
(227, '08-15', 'Mária'),
(228, '08-16', 'Ábrahám'),
(229, '08-17', 'Jácint'),
(230, '08-18', 'Ilona'),
(231, '08-19', 'Huba'),
(232, '08-20', 'István'),
(233, '08-21', 'Hajna, Sámuel'),
(234, '08-22', 'Menyhért, Mirjam'),
(235, '08-23', 'Bence'),
(236, '08-24', 'Bertalan'),
(237, '08-25', 'Lajos, Patrícia'),
(238, '08-26', 'Izsó'),
(239, '08-27', 'Gáspár'),
(240, '08-28', 'Ágoston'),
(241, '08-29', 'Beatrix, Erna'),
(242, '08-30', 'Rózsa'),
(243, '08-31', 'Bella, Erika'),
(244, '09-01', 'Egon, Egyed'),
(245, '09-02', 'Dorina, Rebeka'),
(246, '09-03', 'Hilda'),
(247, '09-04', 'Rozália'),
(248, '09-05', 'Lőrinc, Viktor'),
(249, '09-06', 'Zakariás'),
(250, '09-07', 'Regina'),
(251, '09-08', 'Adrienn, Mária'),
(252, '09-09', 'Adám'),
(253, '09-10', 'Hunor, Nikolett'),
(254, '09-11', 'Teodóra'),
(255, '09-12', 'Mária'),
(256, '09-13', 'Kornél'),
(257, '09-14', 'Roxána, Szeréna'),
(258, '09-15', 'Enikő, Melitta'),
(259, '09-16', 'Edit'),
(260, '09-17', 'Zsófia'),
(261, '09-18', 'Diána'),
(262, '09-19', 'Vilhelmina'),
(263, '09-20', 'Friderika'),
(264, '09-21', 'Máté, Mirella'),
(265, '09-22', 'Móric'),
(266, '09-23', 'Tekla'),
(267, '09-24', 'Gellért, Mercédesz'),
(268, '09-25', 'Eufrozina, Kende'),
(269, '09-26', 'Jusztina, Pál'),
(270, '09-27', 'Adalbert'),
(271, '09-28', 'Vencel'),
(272, '09-29', 'Mihály'),
(273, '09-30', 'Jeromos'),
(274, '10-01', 'Malvin'),
(275, '10-02', 'Petra'),
(276, '10-03', 'Helga'),
(277, '10-04', 'Ferenc'),
(278, '10-05', 'Aurél'),
(279, '10-06', 'Brúnó, Renáta'),
(280, '10-07', 'Amália'),
(281, '10-08', 'Koppány'),
(282, '10-09', 'Dénes'),
(283, '10-10', 'Gedeon'),
(284, '10-11', 'Brigitta'),
(285, '10-12', 'Miksa'),
(286, '10-13', 'Ede, Kálmán'),
(287, '10-14', 'Helén'),
(288, '10-15', 'Teréz'),
(289, '10-16', 'Gál'),
(290, '10-17', 'Hedvig'),
(291, '10-18', 'Lukács'),
(292, '10-19', 'Nándor'),
(293, '10-20', 'Vendel'),
(294, '10-21', 'Orsolya'),
(295, '10-22', 'Előd'),
(296, '10-23', 'Gyöngyi'),
(297, '10-24', 'Salamon'),
(298, '10-25', 'Bianka, Blanka'),
(299, '10-26', 'Dömötör'),
(300, '10-27', 'Szabina'),
(301, '10-28', 'Simon, Szimonetta'),
(302, '10-29', 'Nárcisz'),
(303, '10-30', 'Alfonz'),
(304, '10-31', 'Farkas'),
(305, '11-01', 'Marianna'),
(306, '11-02', 'Achilles'),
(307, '11-03', 'Győző'),
(308, '11-04', 'Károly'),
(309, '11-05', 'Imre'),
(310, '11-06', 'Lénárd'),
(311, '11-07', 'Rezső'),
(312, '11-08', 'Zsombor'),
(313, '11-09', 'Tivadar'),
(314, '11-10', 'Réka'),
(315, '11-11', 'Márton'),
(316, '11-12', 'Jónás, Renátó'),
(317, '11-13', 'Szilvia'),
(318, '11-14', 'Aliz'),
(319, '11-15', 'Albert, Lipót'),
(320, '11-16', 'Ödön'),
(321, '11-17', 'Gergő, Hortenzia'),
(322, '11-18', 'Jenő'),
(323, '11-19', 'Erzsébet'),
(324, '11-20', 'Jolán'),
(325, '11-21', 'Olivér'),
(326, '11-22', 'Cecília'),
(327, '11-23', 'Kelemen, Klementina'),
(328, '11-24', 'Emma'),
(329, '11-25', 'Katalin'),
(330, '11-26', 'Virág'),
(331, '11-27', 'Virgil'),
(332, '11-28', 'Stefánia'),
(333, '11-29', 'Taksony'),
(334, '11-30', 'Andor, András'),
(335, '12-01', 'Elza'),
(336, '12-02', 'Melinda, Vivien'),
(337, '12-03', 'Ferenc, Olívia'),
(338, '12-04', 'Barbara, Borbála'),
(339, '12-05', 'Vilma'),
(340, '12-06', 'Miklós'),
(341, '12-07', 'Ambrus'),
(342, '12-08', 'Mária'),
(343, '12-09', 'Natália'),
(344, '12-10', 'Judit'),
(345, '12-11', 'Árpád'),
(346, '12-12', 'Gabriella'),
(347, '12-13', 'Luca, Otília'),
(348, '12-14', 'Szilárda'),
(349, '12-15', 'Valér'),
(350, '12-16', 'Aletta, Etelka'),
(351, '12-17', 'Lázár, Olimpia'),
(352, '12-18', 'Auguszta'),
(353, '12-19', 'Viola'),
(354, '12-20', 'Teofil'),
(355, '12-21', 'Tamás'),
(356, '12-22', 'Zénó'),
(357, '12-23', 'Viktória'),
(358, '12-24', 'Adám, Éva'),
(359, '12-25', 'Eugénia'),
(360, '12-26', 'István'),
(361, '12-27', 'János'),
(362, '12-28', 'Kamilla'),
(363, '12-29', 'Tamara, Tamás'),
(364, '12-30', 'Dávid'),
(365, '12-31', 'Szilveszter') ON DUPLICATE KEY UPDATE `nevek` = VALUES(`nevek`);

CREATE TABLE IF NOT EXISTS `notifys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fromid` int(255) NOT NULL,
  `toid` int(255) NOT NULL,
  `notifytype` varchar(100) NOT NULL,
  `readed` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `ratings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `file_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `rating` tinyint(4) NOT NULL CHECK (`rating` between 1 and 5),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `translations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `t_key` varchar(100) NOT NULL,
  `lang_code` varchar(5) NOT NULL,
  `text` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

INSERT INTO `translations` (`t_key`, `lang_code`, `text`) VALUES
('nav_home', 'hu', 'Főoldal'),
('nav_home', 'en', 'Home'),
('nav_upload', 'hu', 'Új jegyzet'),
('nav_upload', 'en', 'New note'),
('nav_messages', 'hu', 'Üzenetek'),
('nav_messages', 'en', 'Messages'),
('nav_login', 'hu', 'Bejelentkezés'),
('nav_login', 'en', 'Login'),
('nav_logout', 'hu', 'Kijelentkezés'),
('nav_logout', 'en', 'Logout'),
('hero_greeting', 'hu', 'Szia,'),
('hero_greeting', 'en', 'Hi,'),
('hero_nameday', 'hu', 'Mai névnap'),
('hero_nameday', 'en', 'Name day today'),
('guest', 'hu', 'Vendég'),
('guest', 'en', 'Guest'),
('footer_copy', 'hu', '&copy; 2025 Jegyzetár'),
('footer_copy', 'en', '&copy; 2025 NoteShare'),
('site_tagline', 'hu', 'Iskolai jegyzeteket megosztó oldal'),
('site_tagline', 'en', 'A platform for sharing school notes'),
('hero_logged_out_subtitle', 'hu', 'Jelentkezz be vagy hozz létre új fiókot az induláshoz.'),
('hero_logged_out_subtitle', 'en', 'Log in or create a new account to get started.'),
('hero_welcome', 'hu', 'Üdvözlünk a Jegyzetár rendszerében!'),
('hero_welcome', 'en', 'Welcome to the NoteShare system!'),
('nameday_none', 'hu', 'Nincs névnap ma.'),
('nameday_none', 'en', 'There is no name day today.'),
('birthday_congrats', 'hu', 'Boldog születésnapot,'),
('birthday_congrats', 'en', 'Happy birthday,'),
('meta_keywords', 'hu', 'iskola, jegyzet, megosztás, tanulás'),
('meta_keywords', 'en', 'school, notes, sharing, studying'),
('nav_new_note_plus', 'hu', '+ Új jegyzet'),
('nav_new_note_plus', 'en', '+ New note'),
('btn_details', 'hu', 'Részletek'),
('btn_details', 'en', 'Details'),
('btn_download', 'hu', 'Letöltés'),
('btn_download', 'en', 'Download'),
('btn_delete', 'hu', 'Törlés'),
('btn_delete', 'en', 'Delete'),
('btn_back_home', 'hu', 'Vissza a főoldalra'),
('btn_back_home', 'en', 'Back to home'),
('btn_back_login', 'hu', 'Vissza a bejelentkezéshez'),
('btn_back_login', 'en', 'Back to login'),
('btn_accept', 'hu', 'Elfogadás'),
('btn_accept', 'en', 'Accept'),
('btn_send', 'hu', 'Küldés'),
('btn_send', 'en', 'Send'),
('btn_send_alt', 'hu', 'Elküldés'),
('btn_send_alt', 'en', 'Send'),
('btn_login_cta', 'hu', 'Lépj be!'),
('btn_login_cta', 'en', 'Log in!'),
('btn_register_cta', 'hu', 'Regisztrálj!'),
('btn_register_cta', 'en', 'Register!'),
('btn_continue_discord', 'hu', 'Folytatás Discorddal'),
('btn_continue_discord', 'en', 'Continue with Discord'),
('btn_go_to_note', 'hu', 'Ugrás a jegyzetre'),
('btn_go_to_note', 'en', 'Go to note'),
('auth_login_title', 'hu', 'Belépés'),
('auth_login_title', 'en', 'Login'),
('auth_register_title', 'hu', 'Regisztráció'),
('auth_register_title', 'en', 'Registration'),
('auth_already_have_account', 'hu', 'Már van fiókod?'),
('auth_already_have_account', 'en', 'Already have an account?'),
('auth_no_account_yet', 'hu', 'Még nincs fiókod?'),
('auth_no_account_yet', 'en', 'Don’t have an account yet?'),
('auth_field_lastname', 'hu', 'Vezetéknév'),
('auth_field_lastname', 'en', 'Last name'),
('auth_field_firstname', 'hu', 'Keresztnév'),
('auth_field_firstname', 'en', 'First name'),
('auth_field_username', 'hu', 'Felhasználónév'),
('auth_field_username', 'en', 'Username'),
('auth_field_username_colon', 'hu', 'Felhasználónév:'),
('auth_field_username_colon', 'en', 'Username:'),
('auth_field_email', 'hu', 'Email'),
('auth_field_email', 'en', 'Email'),
('auth_field_password', 'hu', 'Jelszó'),
('auth_field_password', 'en', 'Password'),
('auth_field_password_again', 'hu', 'Jelszó újra'),
('auth_field_password_again', 'en', 'Repeat password'),
('auth_field_password_again_colon', 'hu', 'Jelszó újra:'),
('auth_field_password_again_colon', 'en', 'Repeat password:'),
('auth_field_birthdate', 'hu', 'Születési dátum'),
('auth_field_birthdate', 'en', 'Date of birth'),
('auth_field_gender', 'hu', 'Nem'),
('auth_field_gender', 'en', 'Gender'),
('auth_gender_male', 'hu', 'Férfi'),
('auth_gender_male', 'en', 'Male'),
('auth_gender_female', 'hu', 'Nő'),
('auth_gender_female', 'en', 'Female'),
('auth_gender_other', 'hu', 'Egyéb'),
('auth_gender_other', 'en', 'Other'),
('auth_field_security_question', 'hu', 'Biztonsági kérdés:'),
('auth_field_security_question', 'en', 'Security question:'),
('auth_field_security_answer', 'hu', 'Biztonsági kérdés válasza:'),
('auth_field_security_answer', 'en', 'Answer to security question:'),
('auth_field_answer', 'hu', 'Válasz'),
('auth_field_answer', 'en', 'Answer'),
('auth_placeholder_start_typing', 'hu', 'Kezdj el gépelni...'),
('auth_placeholder_start_typing', 'en', 'Start typing...'),
('secq_fav_book', 'hu', 'Mi a kedvenc könyved?'),
('secq_fav_book', 'en', 'What is your favourite book?'),
('secq_fav_food', 'hu', 'Mi a kedvenc ételed?'),
('secq_fav_food', 'en', 'What is your favourite food?'),
('secq_birth_city', 'hu', 'Mi a születési városod?'),
('secq_birth_city', 'en', 'What is your birth city?'),
('secq_mothers_maiden', 'hu', 'Mi az édesanyád leánykori neve?'),
('secq_mothers_maiden', 'en', 'What is your mother’s maiden name?'),
('secq_first_pet', 'hu', 'Mi volt az első háziállatod neve?'),
('secq_first_pet', 'en', 'What was the name of your first pet?'),
('forgot_title', 'hu', 'Elfelejtett Jelszó'),
('forgot_title', 'en', 'Forgotten password'),
('forgot_heading', 'hu', 'Jelszó visszaállítása'),
('forgot_heading', 'en', 'Password reset'),
('forgot_new_password', 'hu', 'Új jelszó beállítása'),
('forgot_new_password', 'en', 'Set new password'),
('forgot_new_password_label', 'hu', 'Új jelszó:'),
('forgot_new_password_label', 'en', 'New password:'),
('msg_password_change_success', 'hu', 'A jelszavad sikeresen megváltozott!'),
('msg_password_change_success', 'en', 'Your password has been successfully changed!'),
('msg_passwords_not_match', 'hu', 'A jelszavak nem egyeznek!'),
('msg_passwords_not_match', 'en', 'The passwords do not match!'),
('msg_password_same_as_old', 'hu', 'Az új jelszavad nem egyezhet a régivel.'),
('msg_password_same_as_old', 'en', 'Your new password cannot be the same as the old one.'),
('error_wrong_security_answer', 'hu', 'Helytelen biztonsági válasz!'),
('error_wrong_security_answer', 'en', 'Incorrect security answer!'),
('error_wrong_password', 'hu', 'Hibás jelszó!'),
('error_wrong_password', 'en', 'Incorrect password!'),
('email_change_page_title', 'hu', 'Email cím módosítása'),
('email_change_page_title', 'en', 'Change email address'),
('email_change_title', 'hu', 'Email Módosítás'),
('email_change_title', 'en', 'Email change'),
('email_edit_title', 'hu', 'Email módosítás'),
('email_edit_title', 'en', 'Change email'),
('email_change_label_new', 'hu', 'Új email cím'),
('email_change_label_new', 'en', 'New email address'),
('email_change_label_new_colon', 'hu', 'Új email cím:'),
('email_change_label_new_colon', 'en', 'New email address:'),
('email_change_label_again', 'hu', 'Email cím újra:'),
('email_change_label_again', 'en', 'Email again:'),
('email_change_label_again_short', 'hu', 'Email újra'),
('email_change_label_again_short', 'en', 'Email again'),
('msg_email_change_success', 'hu', 'Az új email címed sikeresen megváltozott!'),
('msg_email_change_success', 'en', 'Your new email address has been successfully changed!'),
('msg_email_same_as_old', 'hu', 'Az új email címed nem egyezhet a régivel.'),
('msg_email_same_as_old', 'en', 'Your new email address cannot be the same as the old one.'),
('msg_emails_not_match', 'hu', 'A két email cím nem egyezik!'),
('msg_emails_not_match', 'en', 'The two email addresses do not match!'),
('msg_email_exists', 'hu', 'Már létezik ilyen email cím!'),
('msg_email_exists', 'en', 'This email address is already in use!'),
('msg_generic_success_change', 'hu', 'Sikeres módosítás!'),
('msg_generic_success_change', 'en', 'Change successful!'),
('msg_file_upload_failed', 'hu', 'A fájl feltöltése sikertelen!'),
('msg_file_upload_failed', 'en', 'File upload failed!'),
('msg_file_uploaded', 'hu', 'A fájl sikeresen feltöltve!'),
('msg_file_uploaded', 'en', 'File uploaded successfully!'),
('msg_only_pdf_mp4_docx', 'hu', 'Csak PDF, MP4 vagy DOCX fájlokat lehet feltölteni!'),
('msg_only_pdf_mp4_docx', 'en', 'Only PDF, MP4 or DOCX files can be uploaded!'),
('msg_storage_create_failed', 'hu', 'Nem sikerült létrehozni a tárhelyet!'),
('msg_storage_create_failed', 'en', 'Failed to create storage!'),
('msg_storage_created', 'hu', 'Tárhely sikeresen létrehozva!'),
('msg_storage_created', 'en', 'Storage created successfully!'),
('msg_user_not_found', 'hu', 'Nincs ilyen felhasználó!'),
('msg_user_not_found', 'en', 'No such user found!'),
('msg_no_permission_admin', 'hu', 'Nincs jogosultságod az admin felület megtekintéséhez.'),
('msg_no_permission_admin', 'en', 'You do not have permission to view the admin panel.'),
('msg_friendid_missing', 'hu', 'Hiba: hiányzó barát azonosító.'),
('msg_friendid_missing', 'en', 'Error: missing friend ID.'),
('msg_invalid_user_id', 'hu', 'Hiányzó vagy érvénytelen felhasználó azonosító!'),
('msg_invalid_user_id', 'en', 'Missing or invalid user identifier!'),
('msg_invalid_profile_id', 'hu', 'Érvénytelen profil azonosító.'),
('msg_invalid_profile_id', 'en', 'Invalid profile ID.'),
('msg_message_empty', 'hu', 'Az üzenet nem lehet üres!'),
('msg_message_empty', 'en', 'The message cannot be empty!'),
('msg_comment_write_error', 'hu', 'Hiba történt a komment írásakor!'),
('msg_comment_write_error', 'en', 'An error occurred while posting the comment!'),
('msg_file_upload_error', 'hu', 'Hiba történt a fájl feltöltésekor.'),
('msg_file_upload_error', 'en', 'An error occurred while uploading the file.'),
('msg_note_not_found', 'hu', 'Jegyzet nem található!'),
('msg_note_not_found', 'en', 'Note not found!'),
('msg_note_missing_or_deleted', 'hu', 'A keresett jegyzet nem létezik vagy törölve lett.'),
('msg_note_missing_or_deleted', 'en', 'The requested note does not exist or has been deleted.'),
('msg_profile_not_found', 'hu', 'A keresett profil nem található.'),
('msg_profile_not_found', 'en', 'The requested profile was not found.'),
('empty_no_comments', 'hu', 'Még nincs komment.'),
('empty_no_comments', 'en', 'There are no comments yet.'),
('empty_no_files', 'hu', 'Még nincsenek feltöltött fájlok.'),
('empty_no_files', 'en', 'There are no uploaded files yet.'),
('empty_no_friends', 'hu', 'Még nincsenek barátaid.'),
('empty_no_friends', 'en', 'You don’t have any friends yet.'),
('empty_no_notifications', 'hu', 'Nincs új értesítésed.'),
('empty_no_notifications', 'en', 'You have no new notifications.'),
('empty_no_messages', 'hu', 'Nincsenek üzenetek.'),
('empty_no_messages', 'en', 'There are no messages.'),
('empty_no_users_search', 'hu', 'Nincs felhasználó találat.'),
('empty_no_users_search', 'en', 'No users found.'),
('empty_no_files_search', 'hu', 'Nincs fájl találat a megadott szűrőkre.'),
('empty_no_files_search', 'en', 'No files match the given filters.'),
('upload_page_title', 'hu', 'Anyag feltöltése'),
('upload_page_title', 'en', 'Upload material'),
('upload_label_file', 'hu', 'Fájl kiválasztása:'),
('upload_label_file', 'en', 'Select file:'),
('upload_label_subject', 'hu', 'Tárgy:'),
('upload_label_subject', 'en', 'Subject:'),
('upload_label_tags', 'hu', 'Kulcsszavak, címkék:'),
('upload_label_tags', 'en', 'Keywords, tags:'),
('upload_label_description', 'hu', 'Leírás'),
('upload_label_description', 'en', 'Description'),
('upload_label_description_colon', 'hu', 'Leírás:'),
('upload_label_description_colon', 'en', 'Description:'),
('upload_btn_upload', 'hu', 'Feltöltés'),
('upload_btn_upload', 'en', 'Upload'),
('upload_heading_uploaded_files', 'hu', 'Feltöltött anyagok'),
('upload_heading_uploaded_files', 'en', 'Uploaded materials'),
('msg_fill_subject_and_tags', 'hu', 'Kérjük, adja meg a tárgyat és a címkéket!'),
('msg_fill_subject_and_tags', 'en', 'Please provide the subject and tags.'),
('label_uploaded_by', 'hu', 'Feltöltötte:'),
('label_uploaded_by', 'en', 'Uploaded by:'),
('label_rating_average', 'hu', 'Átlag értékelés:'),
('label_rating_average', 'en', 'Average rating:'),
('suffix_ratings_short', 'hu', 'ért.'),
('suffix_ratings_short', 'en', 'ratings'),
('suffix_ratings_paren', 'hu', 'ért.)'),
('suffix_ratings_paren', 'en', 'ratings)'),
('suffix_rating_singular', 'hu', 'értékelés)'),
('suffix_rating_singular', 'en', 'rating)'),
('sidebar_top_rated', 'hu', 'Top értékelt'),
('sidebar_top_rated', 'en', 'Top rated'),
('label_new_uploads', 'hu', 'Új feltöltések'),
('label_new_uploads', 'en', 'New uploads'),
('label_new_comment', 'hu', 'Új hozzászólás'),
('label_new_comment', 'en', 'New comment'),
('label_text', 'hu', 'Szöveg'),
('label_text', 'en', 'Text'),
('comments_heading', 'hu', 'Kommentek'),
('comments_heading', 'en', 'Comments'),
('comments_placeholder', 'hu', 'Írj kommentet.'),
('comments_placeholder', 'en', 'Write a comment.'),
('btn_send_rating', 'hu', 'Értékelés küldése'),
('btn_send_rating', 'en', 'Send rating'),
('label_rating', 'hu', 'Értékelés'),
('label_rating', 'en', 'Rating'),
('label_mark', 'hu', 'Jelölés'),
('label_mark', 'en', 'Mark'),
('btn_login_to_rate', 'hu', 'Belépés az értékeléshez'),
('btn_login_to_rate', 'en', 'Log in to rate'),
('label_favorite', 'hu', 'Kedvencezés'),
('label_favorite', 'en', 'Add to favourites'),
('search_label_keyword', 'hu', 'Kulcsszó:'),
('search_label_keyword', 'en', 'Keyword:'),
('search_label_users', 'hu', 'Felhasználók'),
('search_label_users', 'en', 'Users'),
('search_label_files', 'hu', 'Fájlok'),
('search_label_files', 'en', 'Files'),
('search_btn_search', 'hu', 'Keresés'),
('search_btn_search', 'en', 'Search'),
('search_filters_title', 'hu', 'Keresés'),
('search_filters_title', 'en', 'Search'),
('search_placeholder', 'hu', 'Keresés…'),
('search_placeholder', 'en', 'Search…'),
('profile_heading', 'hu', 'Saját fiók'),
('profile_heading', 'en', 'My account'),
('profile_label_name', 'hu', 'Teljes név'),
('profile_label_name', 'en', 'Full name'),
('profile_label_firstname', 'hu', 'Keresztnév'),
('profile_label_firstname', 'en', 'First name'),
('profile_label_lastname', 'hu', 'Vezetéknév'),
('profile_label_lastname', 'en', 'Last name'),
('profile_label_username', 'hu', 'Felhasználó'),
('profile_label_username', 'en', 'User'),
('profile_label_birthdate', 'hu', 'Születési dátum'),
('profile_label_birthdate', 'en', 'Date of birth'),
('profile_label_avatar', 'hu', 'Profilkép'),
('profile_label_avatar', 'en', 'Profile picture'),
('profile_label_avatar_upload', 'hu', 'Profilkép feltöltése'),
('profile_label_avatar_upload', 'en', 'Upload profile picture'),
('admin_title', 'hu', 'Admin Panel'),
('admin_title', 'en', 'Admin Panel'),
('admin_users_manage', 'hu', 'Felhasználók kezelése'),
('admin_users_manage', 'en', 'Manage users'),
('admin_files_manage', 'hu', 'Fájlok kezelése'),
('admin_files_manage', 'en', 'Manage files'),
('admin_comments_manage', 'hu', 'Kommentek kezelése'),
('admin_comments_manage', 'en', 'Manage comments'),
('admin_categories_manage', 'hu', 'Kategóriák kezelése'),
('admin_categories_manage', 'en', 'Manage categories'),
('admin_column_name', 'hu', 'Név'),
('admin_column_name', 'en', 'Name'),
('admin_column_fullname', 'hu', 'Teljes név'),
('admin_column_fullname', 'en', 'Full name'),
('admin_column_username', 'hu', 'Felhasználónév'),
('admin_column_username', 'en', 'Username'),
('admin_column_email', 'hu', 'Email'),
('admin_column_email', 'en', 'Email'),
('admin_column_subject', 'hu', 'Kategória'),
('admin_column_subject', 'en', 'Category'),
('admin_column_action', 'hu', 'Művelet'),
('admin_column_action', 'en', 'Action'),
('notify_title', 'hu', 'Értesítések'),
('notify_title', 'en', 'Notifications'),
('notify_clear_all', 'hu', 'Összes értesítés törlése'),
('notify_clear_all', 'en', 'Clear all notifications'),
('notify_more', 'hu', 'Összes →'),
('notify_more', 'en', 'All →'),
('notify_friend_request_sent_to_you', 'hu', 'A felhasználó küldött neked barátfelkérést.'),
('notify_friend_request_sent_to_you', 'en', 'This user sent you a friend request.'),
('notify_you_sent_request', 'hu', 'Te küldted a barátfelkérést.'),
('notify_you_sent_request', 'en', 'You sent the friend request.'),
('notify_is_your_friend', 'hu', 'Ti már barátok vagytok!'),
('notify_is_your_friend', 'en', 'You are already friends!'),
('notify_marked_as_friend', 'hu', 'barátnak jelölt!'),
('notify_marked_as_friend', 'en', 'marked you as a friend!'),
('notify_commented_post', 'hu', 'hozzászólt egy posztodhoz!'),
('notify_commented_post', 'en', 'commented on your post!'),
('friends_list_title', 'hu', 'Barátaid'),
('friends_list_title', 'en', 'Your friends'),
('friends_request_title', 'hu', 'Barátjelölés'),
('friends_request_title', 'en', 'Friend request'),
('friends_mark_as_friend', 'hu', 'Barátnak jelölés'),
('friends_mark_as_friend', 'en', 'Mark as friend'),
('friends_relationship', 'hu', 'Barátság'),
('friends_relationship', 'en', 'Friendship'),
('friends_already_handled', 'hu', 'Már feldolgozott barátjelölés.'),
('friends_already_handled', 'en', 'This friend request has already been handled.'),
('friends_no_friends_yet', 'hu', 'Még nincsenek barátaid.'),
('friends_no_friends_yet', 'en', 'You don’t have any friends yet.'),
('messages_title', 'hu', 'Üzenetek'),
('messages_title', 'en', 'Messages'),
('messages_no_messages', 'hu', 'Nincsenek üzenetek.'),
('messages_no_messages', 'en', 'There are no messages.'),
('messages_choose_friend', 'hu', 'Válassz egy barátot az üzenetküldéshez.'),
('messages_choose_friend', 'en', 'Choose a friend to start messaging.'),
('messages_placeholder', 'hu', 'Írj egy üzenetet...'),
('messages_placeholder', 'en', 'Write a message...'),
('label_name', 'hu', 'Név'),
('label_name', 'en', 'Name'),
('label_firstname', 'hu', 'Keresztnév'),
('label_firstname', 'en', 'First name'),
('label_lastname', 'hu', 'Vezetéknév'),
('label_lastname', 'en', 'Last name'),
('label_users', 'hu', 'Felhasználók'),
('label_users', 'en', 'Users'),
('label_files', 'hu', 'Fájlok'),
('label_files', 'en', 'Files'),
('label_video', 'hu', 'Videó'),
('label_video', 'en', 'Video'),
('label_new_password_same_error', 'hu', 'Az új jelszavad nem egyezhet a régivel.'),
('label_new_password_same_error', 'en', 'Your new password cannot be the same as the old one.'),
('nav_admin', 'hu', 'Admin Panel'),
('nav_admin', 'en', 'Admin Panel'),
('nav_profil', 'hu', 'Fiók'),
('nav_profil', 'en', 'Account'),
('nav_search', 'hu', 'Keresés'),
('nav_search', 'en', 'Search'),
('nav_notify', 'hu', 'Értesítések'),
('nav_notify', 'en', 'Notifications'),
('note_docx_download_hint', 'hu', '.docx fájl - töltsd le a megnyitáshoz.'),
('note_docx_download_hint', 'en', 'This is a .docx file - download it to open.'),
('nameday_none_today', 'hu', 'Nincs névnap ma.'),
('nameday_none_today', 'en', 'There is no name day today.'),
('meta_description_home', 'hu', 'Iskolai jegyzeteket megosztó oldal'),
('meta_description_home', 'en', 'A site for sharing school notes'),
('meta_keywords_home', 'hu', 'iskola, jegyzet, megosztás, tanulás'),
('meta_keywords_home', 'en', 'school, notes, sharing, learning'),
('home_new_uploads', 'hu', 'Új feltöltések'),
('home_new_uploads', 'en', 'New uploads'),
('home_all_arrow', 'hu', 'Összes →'),
('home_all_arrow', 'en', 'All →'),
('upload_title', 'hu', 'Feltöltés'),
('upload_title', 'en', 'Upload'),
('index_title', 'hu', 'Főoldal'),
('index_title', 'en', 'Home'),
('upload_heading', 'hu', 'Anyag feltöltése'),
('upload_heading', 'en', 'Upload material'),
('upload_label_name', 'hu', 'Anyag neve:'),
('upload_label_name', 'en', 'Material name:'),
('upload_placeholder_name', 'hu', 'pl. Fizika ZH anyag'),
('upload_placeholder_name', 'en', 'e.g. Physics test material'),
('upload_placeholder_description', 'hu', 'Rövid leírás az anyagról...'),
('upload_placeholder_description', 'en', 'Short description of the material...'),
('upload_placeholder_subject', 'hu', 'pl. fizika, történelem'),
('upload_placeholder_subject', 'en', 'e.g. physics, history'),
('upload_placeholder_tags', 'hu', 'pl. ZH, jegyzet, beadandó'),
('upload_placeholder_tags', 'en', 'e.g. test, notes, assignment'),
('profile_title', 'hu', 'Fiók'),
('profile_title', 'en', 'Account'),
('profile_of', 'hu', 'profilja'),
('profile_of', 'en', 's profile'),
('profile_data', 'hu', 'Profil adatok'),
('profile_data', 'en', 'Profile information'),
('profile_fullname', 'hu', 'Teljes név'),
('profile_fullname', 'en', 'Full name'),
('profile_username', 'hu', 'Felhasználónév'),
('profile_username', 'en', 'Username'),
('btn_edit_email', 'hu', 'Email szerkesztése'),
('btn_edit_email', 'en', 'Edit email'),
('btn_upload_profile_pic', 'hu', 'Profilkép feltöltése'),
('btn_upload_profile_pic', 'en', 'Upload profile picture'),
('btn_add_friend', 'hu', 'Barátnak jelölés'),
('btn_add_friend', 'en', 'Add friend'),
('profile_friendship', 'hu', 'Barátság'),
('profile_friendship', 'en', 'Friendship'),
('friend_status_friends', 'hu', 'Ti már barátok vagytok!'),
('friend_status_friends', 'en', 'You are already friends!'),
('friend_status_sent_by_you', 'hu', 'Te küldted a barátfelkérést.'),
('friend_status_sent_by_you', 'en', 'You sent the friend request.'),
('friend_status_sent_to_you', 'hu', 'A felhasználó küldött neked barátfelkérést.'),
('friend_status_sent_to_you', 'en', 'This user sent you a friend request.'),
('profile_uploaded_files', 'hu', 'Feltöltött anyagok'),
('profile_uploaded_files', 'en', 'Uploaded materials'),
('label_subject', 'hu', 'Tárgy:'),
('label_subject', 'en', 'Subject:'),
('label_tags', 'hu', 'Címkék:'),
('label_tags', 'en', 'Tags:'),
('docx_warning', 'hu', 'Ez egy .docx fájl. A megtekintéshez töltsd le és nyisd meg Microsoft Word-ben.'),
('docx_warning', 'en', 'This is a .docx file. Download it and open it in Microsoft Word.'),
('bday_title', 'hu', 'Boldog születésnapot,'),
('bday_title', 'en', 'Happy Birthday,'),
('bday_message', 'hu', 'Kívánunk sok sikert és rengeteg kreatív ötletet!'),
('bday_message', 'en', 'We wish you lots of success and many creative ideas!'),
('profile_picture_alt', 'hu', 'Profilkép'),
('profile_picture_alt', 'en', 'Profile picture'),
('profile_registration', 'hu', 'Regisztráció'),
('profile_registration', 'en', 'Registration'),
('btn_delete_file', 'hu', 'Törlés'),
('btn_delete_file', 'en', 'Delete'),
('search_title', 'hu', 'Keresés'),
('search_title', 'en', 'Search'),
('search_keyword', 'hu', 'Kulcsszó:'),
('search_keyword', 'en', 'Keyword:'),
('search_scope_label', 'hu', 'Keresés típusa'),
('search_scope_label', 'en', 'Search scope'),
('search_scope_all', 'hu', 'Mindkettő'),
('search_scope_all', 'en', 'Both'),
('search_scope_files', 'hu', 'Csak fájlok'),
('search_scope_files', 'en', 'Files only'),
('search_scope_users', 'hu', 'Csak felhasználók'),
('search_scope_users', 'en', 'Users only'),
('search_type_label', 'hu', 'Fájltípus'),
('search_type_label', 'en', 'File type'),
('search_type_all', 'hu', 'Összes fájl'),
('search_type_all', 'en', 'All files'),
('search_type_pdf', 'hu', 'PDF'),
('search_type_pdf', 'en', 'PDF'),
('search_type_mp4', 'hu', 'Videó (MP4)'),
('search_type_mp4', 'en', 'Video (MP4)'),
('search_type_docx', 'hu', 'Word (DOCX)'),
('search_type_docx', 'en', 'Word (DOCX)'),
('search_sort_label', 'hu', 'Rendezés'),
('search_sort_label', 'en', 'Sort by'),
('search_sort_new', 'hu', 'Legújabb elöl'),
('search_sort_new', 'en', 'Newest first'),
('search_sort_old', 'hu', 'Legrégebbi elöl'),
('search_sort_old', 'en', 'Oldest first'),
('search_sort_top', 'hu', 'Top értékelt'),
('search_sort_top', 'en', 'Top rated'),
('search_btn', 'hu', 'Keresés'),
('search_btn', 'en', 'Search'),
('pill_pdf', 'hu', 'PDF'),
('pill_pdf', 'en', 'PDF'),
('pill_video', 'hu', 'Videó'),
('pill_video', 'en', 'Video'),
('pill_word', 'hu', 'Word'),
('pill_word', 'en', 'Word'),
('pill_top_rated', 'hu', 'Top értékelt'),
('pill_top_rated', 'en', 'Top rated'),
('pill_users', 'hu', 'Felhasználók'),
('pill_users', 'en', 'Users'),
('result_users', 'hu', 'Felhasználók'),
('result_users', 'en', 'Users'),
('result_files', 'hu', 'Fájlok'),
('result_files', 'en', 'Files'),
('empty_no_users', 'hu', 'Nincs felhasználó találat.'),
('empty_no_users', 'en', 'No matching users found.'),
('empty_no_files_filter', 'hu', 'Nincs fájl találat a megadott szűrőkre.'),
('empty_no_files_filter', 'en', 'No files match the selected filters.'),
('video_fallback', 'hu', 'A böngésződ nem támogatja a video lejátszást.'),
('video_fallback', 'en', 'Your browser does not support video playback.'),
('rating_average', 'hu', 'Átlag értékelés:'),
('rating_average', 'en', 'Average rating:'),
('rating_count_suffix', 'hu', 'ért.'),
('rating_count_suffix', 'en', 'ratings'),
('notif_friend_request_title', 'hu', 'Barátjelölés'),
('notif_friend_request_title', 'en', 'Friend request'),
('notif_friend_marked_you', 'hu', 'barátnak jelölt!'),
('notif_friend_marked_you', 'en', 'sent you a friend request!'),
('btn_accept_friend', 'hu', 'Elfogadás'),
('btn_accept_friend', 'en', 'Accept'),
('notif_friend_already_processed', 'hu', 'Már feldolgozott barátjelölés.'),
('notif_friend_already_processed', 'en', 'This friend request has already been handled.'),
('notif_new_comment_title', 'hu', 'Új hozzászólás'),
('notif_new_comment_title', 'en', 'New comment'),
('notif_comment_your_post', 'hu', 'hozzászólt egy posztodhoz!'),
('notif_comment_your_post', 'en', 'commented on one of your posts!'),
('btn_delete_all_notifications', 'hu', 'Összes értesítés törlése'),
('btn_delete_all_notifications', 'en', 'Delete all notifications'),
('messages_friends_heading', 'hu', 'Barátaid'),
('messages_friends_heading', 'en', 'Your friends'),
('messages_no_friends', 'hu', 'Még nincsenek barátaid.'),
('messages_no_friends', 'en', 'You have no friends yet.'),
('messages_friend_not_found', 'hu', 'A kiválasztott felhasználó nem található.'),
('messages_friend_not_found', 'en', 'The selected user could not be found.'),
('msg_message_send_error', 'hu', 'Hiba történt az üzenet küldésekor.'),
('msg_message_send_error', 'en', 'An error occurred while sending the message.'),
('auth_page_title', 'hu', 'Bejelentkezés'),
('auth_page_title', 'en', 'Log in'),
('auth_welcome_title', 'hu', 'Üdvözlünk a Jegyzetár rendszerében!'),
('auth_welcome_title', 'en', 'Welcome to the Jegyzetár system!'),
('auth_welcome_subtitle', 'hu', 'Jelentkezz be vagy hozz létre új fiókot az induláshoz.'),
('auth_welcome_subtitle', 'en', 'Log in or create a new account to get started.'),
('auth_login_heading', 'hu', 'Bejelentkezés'),
('auth_login_heading', 'en', 'Log in'),
('label_username', 'hu', 'Felhasználónév'),
('label_username', 'en', 'Username'),
('label_password', 'hu', 'Jelszó'),
('label_password', 'en', 'Password'),
('auth_btn_login', 'hu', 'Belépés'),
('auth_btn_login', 'en', 'Log in'),
('auth_forgot_password', 'hu', 'Elfelejtetted a jelszavad?'),
('auth_forgot_password', 'en', 'Forgot your password?'),
('auth_no_account', 'hu', 'Még nincs fiókod?'),
('auth_no_account', 'en', 'Don’t have an account yet?'),
('auth_link_register', 'hu', 'Regisztrálj!'),
('auth_link_register', 'en', 'Sign up!'),
('auth_register_heading', 'hu', 'Regisztráció'),
('auth_register_heading', 'en', 'Registration'),
('label_birthdate', 'hu', 'Születési dátum'),
('label_birthdate', 'en', 'Date of birth'),
('label_gender', 'hu', 'Nem'),
('label_gender', 'en', 'Gender'),
('gender_male', 'hu', 'Férfi'),
('gender_male', 'en', 'Male'),
('gender_female', 'hu', 'Nő'),
('gender_female', 'en', 'Female'),
('gender_other', 'hu', 'Egyéb'),
('gender_other', 'en', 'Other'),
('label_email', 'hu', 'Email'),
('label_email', 'en', 'Email'),
('label_password_again', 'hu', 'Jelszó újra'),
('label_password_again', 'en', 'Password again'),
('auth_security_question_label', 'hu', 'Biztonsági kérdés:'),
('auth_security_question_label', 'en', 'Security question:'),
('auth_security_answer_label', 'hu', 'Válasz'),
('auth_security_answer_label', 'en', 'Answer'),
('auth_btn_register', 'hu', 'Regisztráció'),
('auth_btn_register', 'en', 'Register'),
('auth_have_account', 'hu', 'Már van fiókod?'),
('auth_have_account', 'en', 'Already have an account?'),
('auth_link_login', 'hu', 'Lépj be!'),
('auth_link_login', 'en', 'Log in!'),
('auth_continue_with_discord', 'hu', 'Folytatás Discorddal'),
('auth_continue_with_discord', 'en', 'Continue with Discord'),
('sec_q_favorite_book', 'hu', 'Mi a kedvenc könyved?'),
('sec_q_favorite_book', 'en', 'What is your favorite book?'),
('sec_q_first_pet_name', 'hu', 'Mi volt az első háziállatod neve?'),
('sec_q_first_pet_name', 'en', 'What was the name of your first pet?'),
('sec_q_mother_maiden_name', 'hu', 'Mi az édesanyád leánykori neve?'),
('sec_q_mother_maiden_name', 'en', 'What is your mother’s maiden name?'),
('sec_q_birth_city', 'hu', 'Mi a születési városod?'),
('sec_q_birth_city', 'en', 'What is your birth city?'),
('sec_q_favorite_food', 'hu', 'Mi a kedvenc ételed?'),
('sec_q_favorite_food', 'en', 'What is your favorite food?'),
('msg_storage_failed', 'hu', 'Nem sikerült létrehozni a tárhelyet!'),
('msg_storage_failed', 'en', 'Failed to create storage!'),
('msg_username_exists', 'hu', 'Már létezik ilyen felhasználó!'),
('msg_username_exists', 'en', 'This username is already taken!'),
('msg_wrong_password', 'hu', 'Hibás jelszó!'),
('msg_wrong_password', 'en', 'Incorrect password!'),
('msg_registration_failed', 'hu', 'Hiba történt a regisztráció során.'),
('msg_registration_failed', 'en', 'An error occurred during registration.'),
('email_edit_heading_main', 'hu', 'Email cím módosítása'),
('email_edit_heading_main', 'en', 'Change email address'),
('email_edit_heading_new', 'hu', 'Új email cím'),
('email_edit_heading_new', 'en', 'New email address'),
('label_new_email', 'hu', 'Új email cím:'),
('label_new_email', 'en', 'New email address:'),
('label_new_email_again', 'hu', 'Email cím újra:'),
('label_new_email_again', 'en', 'Email address again:'),
('placeholder_email', 'hu', 'Email'),
('placeholder_email', 'en', 'Email'),
('placeholder_email_again', 'hu', 'Email újra'),
('placeholder_email_again', 'en', 'Email again'),
('label_security_answer_full', 'hu', 'Biztonsági kérdés válasza:'),
('label_security_answer_full', 'en', 'Answer to the security question:'),
('placeholder_security_answer', 'hu', 'Válasz'),
('placeholder_security_answer', 'en', 'Answer'),
('btn_submit', 'hu', 'Elküldés'),
('btn_submit', 'en', 'Submit'),
('btn_back_profile', 'hu', 'Vissza a profilhoz'),
('btn_back_profile', 'en', 'Back to profile'),
('change_success_title', 'hu', 'Sikeres módosítás!'),
('change_success_title', 'en', 'Change successful!'),
('email_edit_success_text', 'hu', 'Az új email címed sikeresen megváltozott!'),
('email_edit_success_text', 'en', 'Your email address has been successfully updated!'),
('msg_wrong_security_answer', 'hu', 'Helytelen biztonsági válasz!'),
('msg_wrong_security_answer', 'en', 'Incorrect security answer!'),
('placeholder_username', 'hu', 'Felhasználónév'),
('placeholder_username', 'en', 'Username'),
('password_forgot_title', 'hu', 'Elfelejtett jelszó'),
('password_forgot_title', 'en', 'Forgot password'),
('password_reset_heading_main', 'hu', 'Jelszó visszaállítása'),
('password_reset_heading_main', 'en', 'Password reset'),
('password_reset_heading_new', 'hu', 'Új jelszó beállítása'),
('password_reset_heading_new', 'en', 'Set a new password'),
('label_new_password', 'hu', 'Új jelszó:'),
('label_new_password', 'en', 'New password:'),
('placeholder_password', 'hu', 'Jelszó'),
('placeholder_password', 'en', 'Password'),
('placeholder_password_again', 'hu', 'Jelszó újra'),
('placeholder_password_again', 'en', 'Password again'),
('btn_change_password', 'hu', 'Jelszó módosítása'),
('btn_change_password', 'en', 'Change password'),
('password_change_success_text', 'hu', 'A jelszavad sikeresen megváltozott!'),
('password_change_success_text', 'en', 'Your password has been successfully changed!'),
('btn_go_to_login', 'hu', 'Bejelentkezés'),
('btn_go_to_login', 'en', 'Back to login'),
('link_back_to_login', 'hu', 'Vissza a bejelentkezéshez'),
('link_back_to_login', 'en', 'Back to login screen'),
('footer_developers_label', 'hu', 'Fejlesztők'),
('footer_developers_label', 'en', 'Developers'),
('footer_github_link', 'hu', 'GitHub'),
('footer_github_link', 'en', 'GitHub'),
('footer_rights', 'hu', '© 2025 Jegyzetár'),
('footer_rights', 'en', '© 2025 Jegyzetár'),
('nav_home', 'de', 'Startseite'),
('nav_upload', 'de', 'Hochladen'),
('nav_messages', 'de', 'Nachrichten'),
('nav_login', 'de', 'Anmelden'),
('nav_logout', 'de', 'Abmelden'),
('hero_greeting', 'de', 'Hallo'),
('hero_nameday', 'de', 'Namenstag heute'),
('guest', 'de', 'Gast'),
('footer_copy', 'de', '© 2025 Jegyzetár'),
('site_tagline', 'de', 'Plattform zum Teilen von Schulnotizen'),
('hero_logged_out_subtitle', 'de', 'Melde dich an oder erstelle ein Konto, um zu starten.'),
('hero_welcome', 'de', 'Willkommen im Jegyzetár-System!'),
('nameday_none', 'de', 'Heute gibt es keinen Namenstag.'),
('birthday_congrats', 'de', 'Alles Gute zum Geburtstag,'),
('meta_keywords', 'de', 'Schule, Notizen, Teilen, Lernen'),
('btn_details', 'de', 'Details'),
('btn_download', 'de', 'Herunterladen'),
('btn_delete', 'de', 'Löschen'),
('btn_back_home', 'de', 'Zur Startseite'),
('btn_back_login', 'de', 'Zur Anmeldung'),
('btn_accept', 'de', 'Akzeptieren'),
('btn_send', 'de', 'Senden'),
('btn_send_alt', 'de', 'Senden'),
('btn_login_cta', 'de', 'Jetzt anmelden'),
('btn_register_cta', 'de', 'Registrieren'),
('btn_continue_discord', 'de', 'Mit Discord fortfahren'),
('btn_go_to_note', 'de', 'Zur Notiz'),
('footer_developers_label', 'de', 'Entwickler'),
('footer_github_link', 'de', 'GitHub'),
('footer_rights', 'de', '© 2025 Jegyzetár'),
('site_title', 'de', 'Jegyzetár'),
('meta_description_home', 'de', 'Plattform zum Teilen von Schulnotizen'),
('meta_keywords_home', 'de', 'Schule, Notizen, Teilen, Lernen'),
('nav_notifications', 'de', 'Benachrichtigungen'),
('nav_profile', 'de', 'Profil'),
('nav_register', 'de', 'Registrieren'),
('btn_edit', 'de', 'Bearbeiten'),
('btn_save', 'de', 'Speichern'),
('btn_cancel', 'de', 'Abbrechen'),
('btn_back_profile', 'de', 'Zurück zum Profil'),
('btn_accept_friend', 'de', 'Freundschaft akzeptieren'),
('btn_send_message', 'de', 'Nachricht senden'),
('btn_delete_all_notifications', 'de', 'Alle Benachrichtigungen löschen'),
('nameday_today', 'de', 'Namenstag heute'),
('nameday_none_today', 'de', 'Heute gibt es keinen Namenstag.'),
('empty_no_notifications', 'de', 'Du hast keine neuen Benachrichtigungen.'),
('empty_no_files', 'de', 'Keine Dateien gefunden.'),
('empty_no_users', 'de', 'Keine Benutzer gefunden.'),
('empty_no_messages', 'de', 'Noch keine Nachrichten.'),
('empty_no_friends', 'de', 'Du hast noch keine Freunde.'),
('notify_title', 'de', 'Benachrichtigungen'),
('notif_friend_request_title', 'de', 'Freundschaftsanfrage'),
('notif_friend_marked_you', 'de', 'hat dich als Freund markiert!'),
('nofif_friend_already_processed', 'de', 'Freundschaftsanfrage bereits bearbeitet.'),
('notif_new_comment_title', 'de', 'Neuer Kommentar'),
('notif_comment_your_post', 'de', 'hat deinen Beitrag kommentiert.'),
('notify_mark_all_read', 'de', 'Alle als gelesen markieren'),
('search_title', 'de', 'Suche'),
('search_keyword', 'de', 'Suchbegriff'),
('search_placeholder', 'de', 'Suche...'),
('search_scope_all', 'de', 'Alles'),
('search_scope_files', 'de', 'Nur Dateien'),
('search_scope_users', 'de', 'Nur Benutzer'),
('search_type_all', 'de', 'Alle Dateitypen'),
('search_type_pdf', 'de', 'PDF'),
('search_type_mp4', 'de', 'Video (MP4)'),
('search_type_docx', 'de', 'Word (DOCX)'),
('search_sort_new', 'de', 'Neueste zuerst'),
('search_sort_old', 'de', 'Älteste zuerst'),
('search_sort_top', 'de', 'Top bewertet'),
('profile_title', 'de', 'Profil'),
('profile_edit', 'de', 'Profil bearbeiten'),
('profile_email', 'de', 'E-Mail'),
('profile_username', 'de', 'Benutzername'),
('profile_birthdate', 'de', 'Geburtsdatum'),
('profile_gender', 'de', 'Geschlecht'),
('profile_registration_date', 'de', 'Registrierungsdatum'),
('gender_male', 'de', 'Männlich'),
('gender_female', 'de', 'Weiblich'),
('gender_other', 'de', 'Divers'),
('email_edit_title', 'de', 'E-Mail ändern'),
('email_new', 'de', 'Neue E-Mail-Adresse'),
('email_new_repeat', 'de', 'Neue E-Mail-Adresse wiederholen'),
('email_change_success', 'de', 'E-Mail erfolgreich geändert!'),
('password_reset_title', 'de', 'Passwort zurücksetzen'),
('password_new', 'de', 'Neues Passwort'),
('password_new_repeat', 'de', 'Passwort wiederholen'),
('password_change_success', 'de', 'Das Passwort wurde erfolgreich geändert!'),
('auth_page_title', 'de', 'Anmeldung'),
('auth_welcome_title', 'de', 'Willkommen im Jegyzetár-System!'),
('auth_welcome_subtitle', 'de', 'Melde dich an oder erstelle ein neues Konto, um zu starten.'),
('auth_login_heading', 'de', 'Anmeldung'),
('auth_register_heading', 'de', 'Registrierung'),
('label_username', 'de', 'Benutzername'),
('label_password', 'de', 'Passwort'),
('label_lastname', 'de', 'Nachname'),
('label_firstname', 'de', 'Vorname'),
('label_birthdate', 'de', 'Geburtsdatum'),
('label_gender', 'de', 'Geschlecht'),
('label_email', 'de', 'E-Mail'),
('label_password_again', 'de', 'Passwort erneut'),
('auth_security_question_label', 'de', 'Sicherheitsfrage:'),
('auth_security_answer_label', 'de', 'Antwort'),
('auth_forgot_password', 'de', 'Passwort vergessen?'),
('auth_btn_login', 'de', 'Anmelden'),
('auth_btn_register', 'de', 'Registrieren'),
('auth_continue_with_discord', 'de', 'Mit Discord fortfahren'),
('auth_no_account', 'de', 'Du hast noch kein Konto?'),
('auth_link_register', 'de', 'Registriere dich!'),
('auth_have_account', 'de', 'Du hast schon ein Konto?'),
('auth_link_login', 'de', 'Melde dich an!'),
('sec_q_favorite_book', 'de', 'Was ist dein Lieblingsbuch?'),
('sec_q_first_pet_name', 'de', 'Wie hieß dein erstes Haustier?'),
('sec_q_mother_maiden_name', 'de', 'Wie lautet der Mädchenname deiner Mutter?'),
('sec_q_birth_city', 'de', 'In welcher Stadt bist du geboren?'),
('sec_q_favorite_food', 'de', 'Was ist dein Lieblingsessen?'),
('msg_storage_created', 'de', 'Speicher wurde erfolgreich erstellt!'),
('msg_storage_failed', 'de', 'Speicher konnte nicht erstellt werden!'),
('msg_storage_create_failed', 'de', 'Speicher konnte nicht erstellt werden!'),
('msg_passwords_not_match', 'de', 'Die Passwörter stimmen nicht überein!'),
('msg_email_exists', 'de', 'Diese E-Mail-Adresse wird bereits verwendet!'),
('msg_username_exists', 'de', 'Dieser Benutzername ist bereits vergeben!'),
('msg_wrong_password', 'de', 'Falsches Passwort!'),
('msg_user_not_found', 'de', 'Es wurde kein solcher Benutzer gefunden!'),
('msg_registration_failed', 'de', 'Bei der Registrierung ist ein Fehler aufgetreten.'),
('msg_wrong_security_answer', 'de', 'Falsche Antwort auf die Sicherheitsfrage!'),
('msg_invalid_user_id', 'de', 'Fehlende oder ungültige Benutzer-ID!'),
('msg_email_same_as_old', 'de', 'Deine neue E-Mail-Adresse darf nicht mit der alten übereinstimmen.'),
('msg_emails_not_match', 'de', 'Die zwei E-Mail-Adressen stimmen nicht überein!'),
('msg_password_same_as_old', 'de', 'Dein neues Passwort darf nicht mit dem alten übereinstimmen.'),
('email_edit_heading_main', 'de', 'E-Mail-Adresse ändern'),
('email_edit_heading_new', 'de', 'Neue E-Mail-Adresse'),
('label_new_email', 'de', 'Neue E-Mail-Adresse:'),
('label_new_email_again', 'de', 'E-Mail-Adresse erneut:'),
('placeholder_email', 'de', 'E-Mail'),
('placeholder_email_again', 'de', 'E-Mail erneut'),
('placeholder_username', 'de', 'Benutzername'),
('label_security_answer_full', 'de', 'Antwort auf die Sicherheitsfrage:'),
('placeholder_security_answer', 'de', 'Antwort'),
('btn_submit', 'de', 'Absenden'),
('change_success_title', 'de', 'Änderung erfolgreich!'),
('email_edit_success_text', 'de', 'Deine neue E-Mail-Adresse wurde erfolgreich gespeichert!'),
('password_forgot_title', 'de', 'Passwort vergessen'),
('password_reset_heading_main', 'de', 'Passwort zurücksetzen'),
('password_reset_heading_new', 'de', 'Neues Passwort festlegen'),
('label_new_password', 'de', 'Neues Passwort:'),
('placeholder_password', 'de', 'Passwort'),
('placeholder_password_again', 'de', 'Passwort erneut'),
('btn_change_password', 'de', 'Passwort ändern'),
('password_change_success_text', 'de', 'Dein Passwort wurde erfolgreich geändert!'),
('btn_go_to_login', 'de', 'Zur Anmeldung'),
('link_back_to_login', 'de', 'Zurück zum Anmeldebildschirm'),
('home_new_uploads', 'de', 'Neue Uploads'),
('home_all_arrow', 'de', 'Alle →'),
('messages_title', 'de', 'Nachrichten'),
('messages_friends_heading', 'de', 'Deine Freunde'),
('messages_no_friends', 'de', 'Du hast noch keine Freunde.'),
('messages_no_messages', 'de', 'Noch keine Nachrichten.'),
('messages_placeholder', 'de', 'Schreibe eine Nachricht...'),
('messages_choose_friend', 'de', 'Wähle einen Freund, um eine Nachricht zu schreiben.'),
('messages_friend_not_found', 'de', 'Der ausgewählte Benutzer wurde nicht gefunden.'),
('btn_upload_profile_pic', 'de', 'Profilbild hochladen'),
('label_subject', 'de', 'Fach'),
('label_tags', 'de', 'Schlagwörter'),
('label_rating_average', 'de', 'Durchschnittliche Bewertung:'),
('rating_average_label', 'de', 'Durchschnittliche Bewertung'),
('rating_count_suffix', 'de', 'Bewertungen'),
('suffix_rating_singular', 'de', 'Bewertung'),
('suffix_rating_plural', 'de', 'Bewertungen'),
('upload_page_title', 'de', 'Hochladen'),
('upload_title', 'de', 'Hochladen'),
('upload_heading', 'de', 'Neue Notiz hochladen'),
('upload_heading_uploaded_files', 'de', 'Deine hochgeladenen Dateien'),
('upload_label_name', 'de', 'Titel:'),
('upload_label_subject', 'de', 'Fach:'),
('upload_label_description', 'de', 'Beschreibung:'),
('upload_label_description_colon', 'de', 'Beschreibung:'),
('upload_label_tags', 'de', 'Schlagwörter:'),
('upload_label_file', 'de', 'Datei:'),
('upload_placeholder_name', 'de', 'z. B. Physik-Testmaterial'),
('upload_placeholder_subject', 'de', 'z. B. Physik, Geschichte'),
('upload_placeholder_description', 'de', 'Kurze Beschreibung des Materials...'),
('upload_placeholder_tags', 'de', 'z. B. Test, Notizen, Abgabe'),
('upload_btn_upload', 'de', 'Hochladen'),
('msg_file_upload_success', 'de', 'Die Datei wurde erfolgreich hochgeladen!'),
('msg_file_upload_failed', 'de', 'Beim Hochladen der Datei ist ein Fehler aufgetreten.'),
('msg_file_upload_error', 'de', 'Beim Hochladen der Datei ist ein Fehler aufgetreten.'),
('msg_invalid_filetype', 'de', 'Dieser Dateityp ist nicht erlaubt.'),
('msg_no_file_selected', 'de', 'Es wurde keine Datei ausgewählt.'),
('docx_warning', 'de', 'Dies ist eine .docx-Datei. Lade sie herunter und öffne sie in Microsoft Word.'),
('video_fallback', 'de', 'Dein Browser unterstützt die Videowiedergabe nicht.'),
('note_details_title', 'de', 'Notizdetails'),
('note_uploaded_by', 'de', 'Hochgeladen von'),
('note_uploaded_at', 'de', 'Hochgeladen am'),
('note_subject', 'de', 'Fach'),
('note_description', 'de', 'Beschreibung'),
('note_tags', 'de', 'Tags'),
('note_file_type', 'de', 'Dateityp'),
('note_back_to_search', 'de', 'Zurück zur Suche'),
('file_preview_pdf', 'de', 'PDF-Vorschau'),
('file_preview_mp4', 'de', 'Videovorschau'),
('file_preview_docx', 'de', 'Dies ist eine DOCX-Datei. Lade sie herunter, um sie in Microsoft Word zu öffnen.'),
('file_preview_not_supported', 'de', 'Dieser Dateityp kann nicht direkt angezeigt werden.'),
('note_rating_title', 'de', 'Bewertung'),
('note_rating_your_rating', 'de', 'Deine Bewertung'),
('note_rating_average', 'de', 'Durchschnittliche Bewertung'),
('note_rating_total', 'de', 'Anzahl Bewertungen'),
('note_rating_login_needed', 'de', 'Du musst angemeldet sein, um zu bewerten.'),
('note_rating_thanks', 'de', 'Danke für deine Bewertung!'),
('comments_title', 'de', 'Kommentare'),
('comments_none', 'de', 'Keine Kommentare vorhanden.'),
('comments_add_comment', 'de', 'Kommentar hinzufügen'),
('comments_placeholder', 'de', 'Schreibe einen Kommentar...'),
('comments_btn_send', 'de', 'Absenden'),
('msg_comment_added', 'de', 'Kommentar erfolgreich hinzugefügt!'),
('msg_comment_failed', 'de', 'Beim Hinzufügen des Kommentars ist ein Fehler aufgetreten.'),
('file_info_title', 'de', 'Dateiinformationen'),
('file_info_size', 'de', 'Dateigröße'),
('file_info_name', 'de', 'Dateiname'),
('file_info_extension', 'de', 'Erweiterung'),
('file_info_last_modified', 'de', 'Zuletzt geändert'),
('file_info_downloads', 'de', 'Downloads'),
('uploader_profile', 'de', 'Zum Profil'),
('uploader_other_files', 'de', 'Andere Dateien dieses Benutzers'),
('note_btn_download', 'de', 'Datei herunterladen'),
('note_btn_back', 'de', 'Zurück'),
('note_btn_delete', 'de', 'Notiz löschen'),
('note_btn_edit', 'de', 'Notiz bearbeiten'),
('note_delete_confirm_title', 'de', 'Löschen bestätigen'),
('note_delete_confirm_text', 'de', 'Bist du sicher, dass du diese Notiz löschen möchtest?'),
('note_delete_success', 'de', 'Die Notiz wurde gelöscht!'),
('note_delete_failed', 'de', 'Beim Löschen der Notiz ist ein Fehler aufgetreten.'),
('note_related_files', 'de', 'Ähnliche Dateien'),
('note_related_no_files', 'de', 'Keine ähnlichen Dateien gefunden.'),
('msg_email_invalid', 'de', 'Ungültige E-Mail-Adresse'),
('msg_invalid_credentials', 'de', 'Ungültige Anmeldedaten'),
('error_generic', 'de', 'Es ist ein Fehler aufgetreten'),
('msg_profile_update_success', 'de', 'Profil wurde aktualisiert'),
('msg_profile_update_failed', 'de', 'Profilaktualisierung fehlgeschlagen'),
('btn_update', 'de', 'Aktualisieren'),
('btn_change', 'de', 'Ändern'),
('btn_retry', 'de', 'Erneut versuchen'),
('sidebar_top_rated', 'de', 'Top bewertet'),
('pill_top_rated', 'de', 'Top bewertet'),
('admin_categories_manage', 'de', 'Kategorien verwalten'),
('admin_column_action', 'de', 'Aktion'),
('admin_column_email', 'de', 'E-Mail'),
('admin_column_fullname', 'de', 'Vollständiger Name'),
('admin_column_name', 'de', 'Name'),
('admin_column_subject', 'de', 'Kategorie'),
('admin_column_username', 'de', 'Benutzername'),
('admin_comments_manage', 'de', 'Kommentare verwalten'),
('admin_files_manage', 'de', 'Dateien verwalten'),
('admin_title', 'de', 'Adminbereich'),
('admin_users_manage', 'de', 'Benutzer verwalten'),
('auth_already_have_account', 'de', 'Du hast schon ein Konto?'),
('auth_field_answer', 'de', 'Antwort'),
('auth_field_birthdate', 'de', 'Geburtsdatum'),
('auth_field_email', 'de', 'E-Mail'),
('auth_field_firstname', 'de', 'Vorname'),
('auth_field_gender', 'de', 'Geschlecht'),
('auth_field_lastname', 'de', 'Nachname'),
('auth_field_password', 'de', 'Passwort'),
('auth_field_password_again', 'de', 'Passwort erneut'),
('auth_field_password_again_colon', 'de', 'Passwort erneut:'),
('auth_field_security_answer', 'de', 'Antwort auf die Sicherheitsfrage:'),
('auth_field_security_question', 'de', 'Sicherheitsfrage:'),
('auth_field_username', 'de', 'Benutzername'),
('auth_field_username_colon', 'de', 'Benutzername:'),
('auth_gender_female', 'de', 'Weiblich'),
('auth_gender_male', 'de', 'Männlich'),
('auth_gender_other', 'de', 'Divers'),
('auth_login_title', 'de', 'Anmeldung'),
('auth_no_account_yet', 'de', 'Du hast noch kein Konto?'),
('auth_placeholder_start_typing', 'de', 'Fang an zu tippen...'),
('auth_register_title', 'de', 'Registrierung'),
('bday_message', 'de', 'Wir wünschen dir viel Erfolg und viele kreative Ideen!'),
('bday_title', 'de', 'Alles Gute zum Geburtstag,'),
('btn_add_friend', 'de', 'Als Freund markieren'),
('btn_delete_file', 'de', 'Datei löschen'),
('btn_login_to_rate', 'de', 'Zum Bewerten anmelden'),
('btn_send_rating', 'de', 'Bewertung senden'),
('comments_heading', 'de', 'Kommentare'),
('email_change_label_again', 'de', 'E-Mail-Adresse erneut:'),
('email_change_label_again_short', 'de', 'E-Mail erneut'),
('email_change_label_new', 'de', 'Neue E-Mail-Adresse'),
('email_change_label_new_colon', 'de', 'Neue E-Mail-Adresse:'),
('email_change_page_title', 'de', 'E-Mail-Adresse ändern'),
('email_change_title', 'de', 'E-Mail-Änderung'),
('empty_no_comments', 'de', 'Es gibt noch keine Kommentare.'),
('empty_no_files_filter', 'de', 'Keine Dateien entsprechen den ausgewählten Filtern.'),
('empty_no_files_search', 'de', 'Keine Dateien entsprechen den angegebenen Filtern.'),
('empty_no_users_search', 'de', 'Es wurden keine Benutzer gefunden.'),
('error_wrong_password', 'de', 'Falsches Passwort!'),
('error_wrong_security_answer', 'de', 'Falsche Antwort auf die Sicherheitsfrage!'),
('forgot_heading', 'de', 'Passwort zurücksetzen'),
('forgot_new_password', 'de', 'Neues Passwort festlegen'),
('forgot_new_password_label', 'de', 'Neues Passwort:'),
('forgot_title', 'de', 'Passwort vergessen'),
('friend_status_friends', 'de', 'Ihr seid bereits befreundet!'),
('friend_status_sent_by_you', 'de', 'Du hast die Freundschaftsanfrage gesendet.'),
('friend_status_sent_to_you', 'de', 'Dieser Benutzer hat dir eine Freundschaftsanfrage gesendet.'),
('friends_already_handled', 'de', 'Diese Freundschaftsanfrage wurde bereits bearbeitet.'),
('friends_list_title', 'de', 'Deine Freunde'),
('friends_mark_as_friend', 'de', 'Als Freund markieren'),
('friends_no_friends_yet', 'de', 'Du hast noch keine Freunde.'),
('friends_relationship', 'de', 'Freundschaft'),
('friends_request_title', 'de', 'Freundschaftsanfrage'),
('index_title', 'de', 'Startseite'),
('label_favorite', 'de', 'Zu Favoriten hinzufügen'),
('label_files', 'de', 'Dateien'),
('label_mark', 'de', 'Markierung'),
('label_name', 'de', 'Name'),
('label_new_comment', 'de', 'Neuer Kommentar'),
('label_new_password_same_error', 'de', 'Dein neues Passwort darf nicht mit dem alten übereinstimmen.'),
('label_new_uploads', 'de', 'Neue Uploads'),
('label_rating', 'de', 'Bewertung'),
('label_text', 'de', 'Text'),
('label_uploaded_by', 'de', 'Hochgeladen von:'),
('label_users', 'de', 'Benutzer'),
('label_video', 'de', 'Video'),
('msg_comment_write_error', 'de', 'Beim Schreiben des Kommentars ist ein Fehler aufgetreten!'),
('msg_email_change_success', 'de', 'Deine neue E-Mail-Adresse wurde erfolgreich geändert!'),
('msg_file_uploaded', 'de', 'Die Datei wurde erfolgreich hochgeladen!'),
('msg_fill_subject_and_tags', 'de', 'Bitte gib das Fach und die Schlagwörter an!'),
('msg_friendid_missing', 'de', 'Fehler: fehlende Freund-ID.'),
('msg_generic_success_change', 'de', 'Änderung erfolgreich!'),
('msg_invalid_profile_id', 'de', 'Ungültige Profil-ID.'),
('msg_message_empty', 'de', 'Die Nachricht darf nicht leer sein!'),
('msg_message_send_error', 'de', 'Beim Senden der Nachricht ist ein Fehler aufgetreten.'),
('msg_no_permission_admin', 'de', 'Du hast keine Berechtigung, das Admin-Panel zu sehen.'),
('msg_note_missing_or_deleted', 'de', 'Die angeforderte Notiz existiert nicht oder wurde gelöscht.'),
('msg_note_not_found', 'de', 'Notiz nicht gefunden!'),
('msg_only_pdf_mp4_docx', 'de', 'Es können nur PDF-, MP4- oder DOCX-Dateien hochgeladen werden!'),
('msg_password_change_success', 'de', 'Dein Passwort wurde erfolgreich geändert!'),
('msg_profile_not_found', 'de', 'Das angeforderte Profil wurde nicht gefunden.'),
('nav_admin', 'de', 'Admin-Panel'),
('nav_new_note_plus', 'de', '+ Neue Notiz'),
('nav_notify', 'de', 'Benachrichtigungen'),
('nav_profil', 'de', 'Konto'),
('nav_search', 'de', 'Suche'),
('note_docx_download_hint', 'de', 'Dies ist eine .docx-Datei – lade sie herunter, um sie zu öffnen.'),
('notify_clear_all', 'de', 'Alle Benachrichtigungen löschen'),
('notify_commented_post', 'de', 'hat deinen Beitrag kommentiert!'),
('notify_friend_request_sent_to_you', 'de', 'Dieser Benutzer hat dir eine Freundschaftsanfrage gesendet.'),
('notify_is_your_friend', 'de', 'Ihr seid bereits befreundet!'),
('notify_marked_as_friend', 'de', 'hat dich als Freund markiert!'),
('notify_more', 'de', 'Alle →'),
('notify_you_sent_request', 'de', 'Du hast die Freundschaftsanfrage gesendet.'),
('pill_pdf', 'de', 'PDF'),
('pill_users', 'de', 'Benutzer'),
('pill_video', 'de', 'Video'),
('pill_word', 'de', 'Word'),
('profile_data', 'de', 'Profildaten'),
('profile_friendship', 'de', 'Freundschaft'),
('profile_fullname', 'de', 'Vollständiger Name'),
('profile_heading', 'de', 'Mein Konto'),
('profile_label_avatar', 'de', 'Profilbild'),
('profile_label_avatar_upload', 'de', 'Profilbild hochladen'),
('profile_label_birthdate', 'de', 'Geburtsdatum'),
('profile_label_firstname', 'de', 'Vorname'),
('profile_label_lastname', 'de', 'Nachname'),
('profile_label_name', 'de', 'Vollständiger Name'),
('profile_label_username', 'de', 'Benutzer'),
('profile_of', 'de', 'Profil'),
('profile_picture_alt', 'de', 'Profilbild'),
('profile_registration', 'de', 'Registrierung'),
('profile_uploaded_files', 'de', 'Hochgeladene Materialien'),
('rating_average', 'de', 'Durchschnittliche Bewertung:'),
('result_files', 'de', 'Dateien'),
('result_users', 'de', 'Benutzer'),
('search_btn', 'de', 'Suche'),
('search_btn_search', 'de', 'Suche'),
('search_filters_title', 'de', 'Suche'),
('search_label_files', 'de', 'Dateien'),
('search_label_keyword', 'de', 'Suchbegriff:'),
('search_label_users', 'de', 'Benutzer'),
('search_scope_label', 'de', 'Suchbereich'),
('search_sort_label', 'de', 'Sortieren nach'),
('search_type_label', 'de', 'Dateityp'),
('secq_birth_city', 'de', 'Wie heißt deine Geburtsstadt?'),
('secq_fav_book', 'de', 'Was ist dein Lieblingsbuch?'),
('secq_fav_food', 'de', 'Was ist dein Lieblingsessen?'),
('secq_first_pet', 'de', 'Wie hieß dein erstes Haustier?'),
('secq_mothers_maiden', 'de', 'Wie lautet der Mädchenname deiner Mutter?'),
('suffix_ratings_paren', 'de', 'Bewertungen)'),
('suffix_ratings_short', 'de', 'Bew.'),
('sec_q_first_pet_name', 'hu', 'Mi volt az első háziállatod neve?'),
('sec_q_first_pet_name', 'en', 'What was the name of your first pet?'),
('sec_q_first_pet_name', 'de', 'Wie hieß dein erstes Haustier?'),
('sec_q_favorite_food', 'hu', 'Mi a kedvenc ételed?'),
('sec_q_favorite_food', 'en', 'What is your favourite food?'),
('sec_q_favorite_food', 'de', 'Was ist dein Lieblingsessen?'),
('error_all_fields_required', 'hu', 'Minden mező kötelező.'),
('error_all_fields_required', 'en', 'All fields are required.'),
('error_all_fields_required', 'de', 'Alle Felder sind erforderlich.'),
('error_bad_email_format', 'hu', 'Hibás email formátum.'),
('error_bad_email_format', 'en', 'Invalid email format.'),
('error_bad_email_format', 'de', 'Ungültiges E-Mail-Format.'),
('error_security_answer_required', 'hu', 'Biztonsági kérdésre választ kell adnod.'),
('error_security_answer_required', 'en', 'Security question answer is required.'),
('error_security_answer_required', 'de', 'Antwort auf die Sicherheitsfrage erforderlich.'),
('msg_file_upload_error', 'hu', 'Hiba történt a fájl feltöltésekor.'),
('msg_file_upload_error', 'en', 'An error occurred while uploading the file.'),
('msg_file_upload_error', 'de', 'Beim Hochladen der Datei ist ein Fehler aufgetreten.'),
('profile_title', 'hu', 'Profil'),
('profile_title', 'en', 'Profile'),
('profile_title', 'de', 'Profil'),
('meta_description_home', 'hu', 'Iskolai jegyzetek megosztása, letöltése, feltöltése.'),
('meta_description_home', 'en', 'Share, download and upload school notes.'),
('meta_description_home', 'de', 'Schulnotizen teilen, herunterladen und hochladen.'),
('meta_keywords_home', 'hu', 'iskola, jegyzet, megosztás, tanulás'),
('meta_keywords_home', 'en', 'school, notes, sharing, studying'),
('meta_keywords_home', 'de', 'Schule, Notizen, Teilen, Lernen'),
('profile_of', 'hu', 'profilja'),
('profile_of', 'en', 'profile'),
('bday_title', 'hu', 'Boldog születésnapot,'),
('bday_title', 'en', 'Happy birthday,'),
('bday_title', 'de', 'Alles Gute zum Geburtstag,'),
('bday_message', 'hu', 'Kívánunk sok boldogságot!'),
('bday_message', 'en', 'We wish you many happy returns!'),
('bday_message', 'de', 'Wir wünschen dir alles Gute!'),
('btn_upload_profile_pic', 'hu', 'Feltöltés'),
('btn_upload_profile_pic', 'en', 'Upload'),
('btn_upload_profile_pic', 'de', 'Hochladen'),
('nav_favorites', 'hu', 'Kedvenceim'),
('nav_favorites', 'en', 'Favorites'),
('nav_favorites', 'de', 'Favoriten'),
('profile_friendship', 'hu', 'Barátság státusz'),
('profile_friendship', 'en', 'Friendship status'),
('profile_friendship', 'de', 'Freundschaftsstatus'),
('friend_status_friends', 'hu', 'Barátok'),
('friend_status_friends', 'en', 'Friends'),
('friend_status_friends', 'de', 'Freunde'),
('friend_status_sent_by_you', 'hu', 'Kérés elküldve (te)'),
('friend_status_sent_by_you', 'en', 'Request sent (by you)'),
('friend_status_sent_by_you', 'de', 'Anfrage gesendet (von dir)'),
('friend_status_sent_to_you', 'hu', 'Neked küldtek kérelmet'),
('friend_status_sent_to_you', 'en', 'Request sent (to you)'),
('friend_status_sent_to_you', 'de', 'Anfrage gesendet (an dich)'),
('btn_add_friend', 'hu', 'Barát hozzáadása'),
('btn_add_friend', 'en', 'Add friend'),
('btn_add_friend', 'de', 'Freund hinzufügen'),
('profile_data', 'hu', 'Adatok'),
('profile_data', 'en', 'Profile information'),
('profile_data', 'de', 'Profilinformationen'),
('profile_fullname', 'hu', 'Teljes név'),
('profile_fullname', 'en', 'Full name'),
('profile_fullname', 'de', 'Vollständiger Name'),
('profile_username', 'hu', 'Felhasználónév'),
('profile_username', 'en', 'Username'),
('profile_username', 'de', 'Benutzername'),
('profile_email', 'hu', 'Email'),
('profile_email', 'en', 'Email'),
('profile_email', 'de', 'E-Mail'),
('profile_birthdate', 'hu', 'Születésnap'),
('profile_birthdate', 'en', 'Birthday'),
('profile_birthdate', 'de', 'Geburtstag'),
('profile_registration', 'hu', 'Regisztráció dátuma'),
('profile_registration', 'en', 'Registered'),
('profile_registration', 'de', 'Registriert'),
('btn_edit_profile_data', 'hu', 'Adatok szerkesztése'),
('btn_edit_profile_data', 'en', 'Edit profile data'),
('btn_edit_profile_data', 'de', 'Daten bearbeiten'),
('profile_security_intro', 'hu', 'Mielőtt mentenénk az adataidat, állíts be egy biztonsági kérdést is.'),
('profile_security_intro', 'en', 'Before saving your data, set a security question.'),
('profile_security_intro', 'de', 'Bevor wir deine Daten speichern, richte bitte eine Sicherheitsfrage ein.'),
('auth_field_security_question', 'hu', 'Biztonsági kérdés'),
('auth_field_security_question', 'en', 'Security question'),
('auth_field_security_question', 'de', 'Sicherheitsfrage'),
('auth_field_answer', 'hu', 'Válasz'),
('auth_field_answer', 'en', 'Answer'),
('auth_field_answer', 'de', 'Antwort'),
('placeholder_security_answer', 'hu', 'Írd ide a választ'),
('placeholder_security_answer', 'en', 'Enter the answer'),
('placeholder_security_answer', 'de', 'Antwort eingeben'),
('profile_customization', 'hu', 'Profil testreszabása'),
('profile_customization', 'en', 'Profile customization'),
('profile_customization', 'de', 'Profilanpassung'),
('profile_bio', 'hu', 'Bemutatkozás'),
('profile_bio', 'en', 'About'),
('profile_bio', 'de', 'Über mich'),
('css_placeholder', 'hu', '/* Írd ide a CSS-t a profilodhoz */'),
('css_placeholder', 'en', '/* Write the CSS for your profile here */'),
('css_placeholder', 'de', '/* Schreibe hier das CSS für dein Profil */'),
('msg_css_empty_reset', 'hu', 'A CSS mező üres — visszaállítva.'),
('msg_css_empty_reset', 'en', 'CSS field is empty — reset.'),
('msg_css_empty_reset', 'de', 'CSS-Feld ist leer — zurückgesetzt.'),
('msg_css_approved_by_admin', 'hu', 'A CSS csak akkor lép életbe, ha egy admin jóváhagyja.'),
('msg_css_approved_by_admin', 'en', 'The CSS takes effect only after an admin approves it.'),
('msg_css_approved_by_admin', 'de', 'Das CSS tritt erst in Kraft, nachdem ein Admin es genehmigt hat.'),
('css_approval_note', 'hu', 'A CSS csak akkor lép életbe, ha egy admin jóváhagyja.'),
('css_approval_note', 'en', 'The CSS only takes effect after admin approval.'),
('css_approval_note', 'de', 'Das CSS wirkt nur nach Admin-Freigabe.'),
('profile_theme', 'hu', 'Téma'),
('profile_theme', 'en', 'Theme'),
('profile_theme', 'de', 'Thema'),
('profile_theme_default', 'hu', 'Alap (Sötét)'),
('profile_theme_default', 'en', 'Default (Dark)'),
('profile_theme_default', 'de', 'Standard (Dunkel)'),
('profile_theme_pastel', 'hu', 'Pastel'),
('profile_theme_pastel', 'en', 'Pastel'),
('profile_theme_pastel', 'de', 'Pastellfarbe'),
('profile_theme_forest', 'hu', 'Forest'),
('profile_theme_forest', 'en', 'Forest'),
('profile_theme_forest', 'de', 'Wald'),
('profile_theme_light', 'hu', 'Világos'),
('profile_theme_light', 'en', 'Light'),
('profile_theme_light', 'de', 'Hell'),
('btn_save', 'hu', 'Mentés'),
('btn_save', 'en', 'Save'),
('btn_save', 'de', 'Speichern'),
('profile_custom_css_request', 'hu', 'Egyedi CSS kérés'),
('profile_custom_css_request', 'en', 'Custom CSS request'),
('profile_custom_css_request', 'de', 'Benutzerdefinierte CSS-Anfrage'),
('profile_last_request_status', 'hu', 'Utolsó kérésed státusza:'),
('profile_last_request_status', 'en', 'Status of your last request:'),
('profile_last_request_status', 'de', 'Status deiner letzten Anfrage:'),
('profile_custom_css_not_requested', 'hu', 'Még nem adtál le egyedi CSS kérést.'),
('profile_custom_css_not_requested', 'en', 'You have not submitted a custom CSS request yet.'),
('profile_custom_css_not_requested', 'de', 'Du hast noch keine benutzerdefinierte CSS-Anfrage gestellt.'),
('profile_css_tutorial_summary', 'hu', 'Segítség: hogyan írj saját CSS-t a profilodhoz?'),
('profile_css_tutorial_summary', 'en', 'Help: how to write custom CSS for your profile?'),
('profile_css_tutorial_summary', 'de', 'Hilfe: Wie schreibt man eigenes CSS für das Profil?'),
('profile_css_tutorial_intro', 'hu', 'Az itt megadott CSS csak a profilodra fog hatni, miután egy admin jóváhagyta. Nyugodtan használj olyan szelektorokat, mint body, .main, .card, .profile-name, .profile-username, stb.'),
('profile_css_tutorial_intro', 'en', 'The CSS entered here will only affect your profile after an admin approves it. You may use selectors like body, .main, .card, .profile-name, .profile-username, etc.'),
('profile_css_tutorial_intro', 'de', 'Das hier eingegebene CSS wirkt erst auf dein Profil, nachdem ein Admin es freigegeben hat. Du kannst Selektoren wie body, .main, .card, .profile-name, .profile-username usw. verwenden.'),
('profile_css_tutorial_example', 'hu', 'Példa: sötét, "neonos" profil téma — kiindulási alap:'),
('profile_css_tutorial_example', 'en', 'Example: dark, "neon" profile theme — you can use this as a starting point:'),
('profile_css_tutorial_example', 'de', 'Beispiel: dunkles, "neon"-Profilthema — du kannst es als Ausgangspunkt verwenden:'),
('tip_profile_custom_css', 'hu', 'Tipp: ha csak a profilod egy részét akarod módosítani (pl. a gombokat), elég azokat a classokat piszkálni, amik ide tartoznak, pl. .btn-cta, .btn-ghost, .profile-info-item, .profile-badges, .badge-pill.'),
('tip_profile_custom_css', 'en', 'Tip: if you only want to change part of your profile (e.g., the buttons), modify the relevant classes such as .btn-cta, .btn-ghost, .profile-info-item, .profile-badges, .badge-pill.'),
('tip_profile_custom_css', 'de', 'Tipp: Wenn du nur einen Teil deines Profils ändern möchtest (z. B. die Buttons), bearbeite die entsprechenden Klassen wie .btn-cta, .btn-ghost, .profile-info-item, .profile-badges, .badge-pill.'),
('profile_css_label', 'hu', 'CSS kód'),
('profile_css_label', 'en', 'CSS code'),
('profile_css_label', 'de', 'CSS-Code'),
('profile_custom_css_submit', 'hu', 'Egyedi CSS elküldése'),
('profile_custom_css_submit', 'en', 'Submit custom CSS'),
('profile_custom_css_submit', 'de', 'Benutzerdefiniertes CSS senden'),
('profile_custom_css_reset_btn', 'hu', 'Egyedi CSS visszaállítása'),
('profile_custom_css_reset_btn', 'en', 'Reset custom CSS'),
('profile_custom_css_reset_btn', 'de', 'Benutzerdefiniertes CSS zurücksetzen'),
('profile_uploaded_files', 'hu', 'Feltöltött anyagok'),
('profile_uploaded_files', 'en', 'Uploaded files'),
('profile_uploaded_files', 'de', 'Hochgeladene Dateien'),
('label_unknown_user', 'hu', 'ismeretlen'),
('label_unknown_user', 'en', 'unknown'),
('label_unknown_user', 'de', 'unbekannt'),
('btn_details', 'hu', 'Részletek'),
('btn_details', 'en', 'Details'),
('btn_details', 'de', 'Details'),
('btn_download', 'hu', 'Letöltés'),
('btn_download', 'en', 'Download'),
('btn_download', 'de', 'Herunterladen'),
('label_subject', 'hu', 'Tantárgy:'),
('label_subject', 'en', 'Subject:'),
('label_subject', 'de', 'Fach:'),
('docx_warning', 'hu', 'A DOCX fájl megtekintése nem támogatott, töltsd le a fájlt.'),
('docx_warning', 'en', 'Viewing DOCX files is not supported; please download the file.'),
('docx_warning', 'de', 'Die Anzeige von DOCX-Dateien wird nicht unterstützt; bitte lade die Datei herunter.'),
('label_tags', 'hu', 'Címkék:'),
('label_tags', 'en', 'Tags:'),
('label_tags', 'de', 'Tags:'),
('btn_delete_file', 'hu', 'Törlés'),
('btn_delete_file', 'en', 'Delete'),
('btn_delete_file', 'de', 'Löschen'),
('empty_no_files', 'hu', 'Nincs feltöltött fájl.'),
('empty_no_files', 'en', 'No files uploaded.'),
('empty_no_files', 'de', 'Keine Dateien hochgeladen.'),
('msg_profile_update_success', 'hu', 'Profil frissítve ✅'),
('msg_profile_update_success', 'en', 'Profile updated ✅'),
('msg_profile_update_success', 'de', 'Profil aktualisiert ✅') ON DUPLICATE KEY UPDATE `text` = VALUES(`text`);

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lastname` varchar(100) DEFAULT NULL,
  `firstname` varchar(100) DEFAULT NULL,
  `username` varchar(50) NOT NULL,
  `birthdate` date DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `email` varchar(50) NOT NULL,
  `profile_picture` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `security_question` varchar(255) NOT NULL,
  `security_answer` varchar(255) NOT NULL,
  `admin` tinyint(1) NOT NULL,
  `registration_date` datetime DEFAULT NULL,
  `language` varchar(5) NOT NULL DEFAULT 'hu',
  `oauth_provider` varchar(20) DEFAULT NULL,
  `oauth_sub` varchar(191) DEFAULT NULL,
  `email_verified` tinyint(1) NOT NULL DEFAULT 0,
  `bio` text DEFAULT NULL,
  `profile_theme` varchar(32) NOT NULL DEFAULT 'default',
  PRIMARY KEY (`id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `user_badges` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `badge_id` int(11) NOT NULL,
  `granted_by` int(11) DEFAULT NULL,
  `granted_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

CREATE TABLE IF NOT EXISTS `user_custom_css_archive` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `original_request_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `css` mediumtext NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL,
  `created_at` datetime NOT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  `archived_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE IF NOT EXISTS `user_custom_css_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `css` mediumtext NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `reviewed_at` datetime DEFAULT NULL,
  `reviewed_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `badges`
  ADD UNIQUE KEY `slug` (`slug`);

ALTER TABLE `friends`
  ADD KEY `fromid` (`fromid`),
  ADD KEY `toid` (`toid`);

ALTER TABLE `languages`
  ADD UNIQUE KEY `code` (`code`);


ALTER TABLE `ratings`
  ADD UNIQUE KEY `uniq_user_file` (`file_id`,`user_id`),
  ADD KEY `idx_file` (`file_id`),
  ADD KEY `idx_user` (`user_id`);

ALTER TABLE `users`
  ADD UNIQUE KEY `username` (`username`),
  ADD UNIQUE KEY `uniq_oauth` (`oauth_provider`,`oauth_sub`),
  ADD KEY `fk_user_lang` (`language`);

ALTER TABLE `user_badges`
  ADD CONSTRAINT `user_badges_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `user_badges_ibfk_2` FOREIGN KEY (`badge_id`) REFERENCES `badges` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `user_badges_ibfk_3` FOREIGN KEY (`granted_by`) REFERENCES `users` (`id`) ON DELETE SET NULL;

ALTER TABLE `user_custom_css_requests`
  ADD CONSTRAINT `fk_css_reviewer` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  ADD CONSTRAINT `fk_css_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
COMMIT;
